settings:
  title: 'kwa@status'
  url: 'https://s.kwaa.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '一切正常'
  notAllmonitorsOperational: '并非一切正常'
  monitorLabelOperational: '正常'
  monitorLabelNotOperational: '離線'
  monitorLabelNoData: '暫無數據'
  dayInHistogramNoData: '暫無數據'
  dayInHistogramOperational: '正常'
  dayInHistogramNotOperational: ' 次事件' # xx incident(s) recorded

monitors:
  - id: kwaa-dev # unique identifier
    name: './kwaa.dev'
    description: '[DATA EXPUNGED]' # default=empty
    url: 'https://kwaa.dev' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: kwaa-moe
    name: '~/kwaa.moe'
    description: 'In Solitude, Where We Are Least Alone.'
    url: 'https://kwaa.moe'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
